services:
  db:
    image: postgres:12
    restart: always
    container_name: ex08_local
    environment:
      - POSTGRES_DB=ex08_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    container_name: ex08_api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ex08_local?sslmode=disable
      PORT: 8080
    links:
      - db
    depends_on:
      - db